import {useEffect,useState} from 'react'
import type {FormEvent} from 'react'
import type {SupabaseClient} from '@supabase/supabase-js'
import type {Role} from './data'
import './knowledge.css'
type Entry={id:string;title:string;content:string;audience:'both'|'intern'|'lead';status:'draft'|'published';version:number;updated_at:string}
type Props={client:SupabaseClient;role:Role;cohortId:string}
export default function Knowledge({client,role,cohortId}:Props){
 const [entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[editor,setEditor]=useState<{item?:Entry}|null>(null),[search,setSearch]=useState('')
 useEffect(()=>{let active=true;setEditor(null);setEntries([]);setError('');if(role!=='lead'){setLoading(false);return}
 setLoading(true);void (async()=>{try{const result=await client.from('ai_knowledge').select('*').eq('cohort_id',cohortId).order('updated_at',{ascending:false});if(result.error)throw result.error;if(active)setEntries(result.data||[])}catch(e){if(active)setError(e instanceof Error?e.message:'Could not load guidance. Refresh and try again.')}finally{if(active)setLoading(false)}})();return()=>{active=false}
 },[client,cohortId,role,revision])
 async function write(operation:()=>PromiseLike<{data:unknown;error:unknown}>,message:string){if(busy||role!=='lead')return;setBusy(true);setError('');setNotice('');try{const r=await operation();if(r.error)throw r.error;if(!Array.isArray(r.data)||!r.data.length)throw new Error('This entry changed or your permissions changed. Keep your text, cancel, and refresh before saving again.');setEditor(null);setRevision(v=>v+1);setNotice(message)}catch(e){setError(e&&typeof e==='object'&&'message'in e?String(e.message):'Could not save. Please try again.')}finally{setBusy(false)}}
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editor||busy)return;const values=new FormData(e.currentTarget);const title=String(values.get('title')||'').trim(),content=String(values.get('content')||'').trim(),audience=String(values.get('audience')||'both');const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;const status=submitter?.value==='published'?'published':'draft';if(!title||!content){setError('Enter a title and guidance before saving.');return}if(title.length>200||content.length>6000||!['both','intern','lead'].includes(audience)){setError('Check the audience and text limits before saving.');return}const payload={title,content,audience,status};void write(()=>editor.item?client.from('ai_knowledge').update(payload).eq('id',editor.item.id).eq('cohort_id',cohortId).eq('version',editor.item.version).select('id'):client.from('ai_knowledge').insert({...payload,cohort_id:cohortId}).select('id'),status==='published'?'Guidance published. New assistant requests can use it.':'Draft saved. The assistant will not use it.')}
 if(role!=='lead')return <section className="panel" role="alert">AI Knowledge editing is available to cohort leads.</section>
 return <section className="panel knowledge"><div className="panel-heading"><div><h2>Guidance your assistant can reference</h2><p className="knowledge-intro">Manage cohort FAQs, fellowship guidelines, and submission instructions. Only published entries for the right audience reach the assistant.</p></div><div className="manager-actions"><button className="text-button" disabled={busy||loading||!!editor} onClick={()=>setRevision(v=>v+1)}>Refresh</button><button className="primary-button" disabled={busy||loading||!!editor} onClick={()=>{setError('');setEditor({})}}>Add guidance</button></div></div>
 <p className="knowledge-boundary">Guidance provides reference content. It cannot change account permissions, security rules, or enable email and calendar actions.</p>
 {error&&<p role="alert" className="auth-error">{error}</p>}{notice&&<p role="status" className="manager-notice">{notice}</p>}
 {editor&&<form className="record-form" onSubmit={save} noValidate aria-busy={busy}><h3>{editor.item?'Edit guidance':'Add guidance'}</h3>{editor.item?.status==='published'&&<p>This entry is currently published. Saving a draft will unpublish it; publishing applies your edits immediately to new assistant requests.</p>}<fieldset disabled={busy}><label>Title<input name="title" defaultValue={editor.item?.title||''} maxLength={200} required/></label><label>Audience<select name="audience" defaultValue={editor.item?.audience||'both'}><option value="both">Leads and interns</option><option value="intern">Interns only</option><option value="lead">Leads only</option></select></label><label className="knowledge-content">Guidance<textarea name="content" defaultValue={editor.item?.content||''} maxLength={6000} rows={10} placeholder="Write approved, factual guidance. Include what interns should do and who to ask when information is missing." required/><span>Plain text · up to 6,000 characters</span></label><div className="manager-actions"><button className="text-button" type="submit" value="draft">Save draft</button><button className="primary-button" type="submit" value="published">Publish guidance</button><button className="text-button" type="button" onClick={()=>{setEditor(null);setError('')}}>Cancel</button></div></fieldset></form>}
 <label className="manager-search">Search guidance<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search titles and guidance"/></label>
 {loading?<p role="status">Loading guidance…</p>:<div className="manager-list">{entries.filter(k=>`${k.title} ${k.content}`.toLowerCase().includes(search.toLowerCase())).map(k=><article className="manager-record" key={k.id}><div className="manager-record-heading"><h3>{k.title}</h3><div className="manager-actions"><button className="text-button" disabled={busy||!!editor} onClick={()=>{setError('');setEditor({item:k})}}>Edit</button>{k.status==='published'&&<button className="text-button" disabled={busy||!!editor} onClick={()=>void write(()=>client.from('ai_knowledge').update({status:'draft'}).eq('id',k.id).eq('cohort_id',cohortId).eq('version',k.version).select('id'),'Guidance unpublished. New assistant requests will not use it.')}>Unpublish</button>}</div></div><p className="manager-meta">{k.status==='published'?'Published':'Draft'} · {k.audience==='both'?'Leads and interns':k.audience==='lead'?'Leads only':'Interns only'} · Version {k.version}</p><details className="knowledge-preview"><summary>Preview guidance</summary><div>{k.content}</div></details></article>)}{!entries.length&&<p>No guidance yet. Add an FAQ or fellowship guideline, save a draft, then publish it when ready.</p>}{entries.length>0&&!entries.some(k=>`${k.title} ${k.content}`.toLowerCase().includes(search.toLowerCase()))&&<p>No guidance matches your search.</p>}</div>}
 </section>
}
